In [1]:
import sys
import os

sys.path.append(os.path.dirname(os.getcwd()))
os.chdir("../")

# Verify MEPS Graph

In [2]:
import torch
import os

graph_dir_path = "/vol/bitbucket/bet20/neural-lam/graphs/multiscale"
static_dir_path = "/vol/bitbucket/bet20/neural-lam/data/meps_example/static"

In [3]:
grid_features = torch.load(os.path.join(static_dir_path, "grid_features.pt"))
print(grid_features.shape)

mesh_features = torch.load(os.path.join(graph_dir_path, "mesh_features.pt"))
print(mesh_features[0].shape)

torch.Size([63784, 4])
torch.Size([6561, 2])


In [4]:
g2m_features = torch.load(os.path.join(graph_dir_path, "g2m_features.pt"))
g2m_edge_index = torch.load(os.path.join(graph_dir_path, "g2m_edge_index.pt"))

print(g2m_edge_index.shape)

gmin, gmax = g2m_edge_index[0].min(), g2m_edge_index[0].max()
mmin, mmax = g2m_edge_index[1].min(), g2m_edge_index[1].max()
print(gmin, gmax, mmin, mmax)
print(gmax - gmin + 1, mmax - mmin + 1)
print(g2m_features.shape[0])

# print(g2m_edge_index.min(dim=1, keepdim=True)[0])
# print(g2m_edge_index.min(dim=1, keepdim=True).values[0])

g2m_edge_index = g2m_edge_index - g2m_edge_index.min(dim=1, keepdim=True)[0]

torch.Size([2, 100656])
tensor(6561) tensor(70344) tensor(0) tensor(6560)
tensor(63784) tensor(6561)
100656


In [5]:
g2m_edge_index

tensor([[    0,     1,     2,  ..., 63781, 63782, 63783],
        [    0,     0,     0,  ...,  6560,  6560,  6560]])

In [6]:
num_rec = g2m_edge_index[1].max() + 1

In [7]:
g2m_edge_index[0] = (
    g2m_edge_index[0] + num_rec
)

print(g2m_edge_index)

tensor([[ 6561,  6562,  6563,  ..., 70342, 70343, 70344],
        [    0,     0,     0,  ...,  6560,  6560,  6560]])


# Sanity Check Graph

In [8]:
import numpy as np
import torch
import os

In [9]:
dir = "./data/era5_uk/static/nwp_xy.npy"
grid_xy = torch.tensor(np.load(dir))
_, lon, lat = grid_xy.shape

graph_name = "uk_graphcast"
graph_dir_path = os.path.join("graphs", graph_name)

In [10]:
print(lon, lat)
print("Local grid nodes", lon * lat)

X, Y = 1440, 721
fraction = (lon * lat) / (X * Y)
print("Global grid nodes", X * Y)
print("Local : Global", fraction)

57 65
Local grid nodes 3705
Global grid nodes 1038240
Local : Global 0.0035685390661118815


### Verify M2M Graph

In [11]:
N_MESH_NODES = 40962
N_MESH_EDGES = 327660 

mesh_features = torch.load(os.path.join(graph_dir_path, "mesh_features.pt"))
m2m_features = torch.load(os.path.join(graph_dir_path, "m2m_features.pt"))
m2m_edge_index = torch.load(os.path.join(graph_dir_path, "m2m_edge_index.pt"))

print(mesh_features[0].shape)
print(m2m_features[0].shape)
print(m2m_edge_index[0].shape)
print(m2m_edge_index[0].unique().shape)

print("Expected mesh nodes", N_MESH_NODES * fraction)
print("Expected mesh edges", N_MESH_EDGES * fraction)

torch.Size([355, 3])
torch.Size([2584, 4])
torch.Size([2, 2584])
torch.Size([355])
Expected mesh nodes 146.1744972260749
Expected mesh edges 1169.2675104022192


### Verify G2M Graph

In [12]:
N_G2M_EDGES = 1618746

g2m_features = torch.load(os.path.join(graph_dir_path, "g2m_features.pt"))
g2m_edge_index = torch.load(os.path.join(graph_dir_path, "g2m_edge_index.pt"))

print(g2m_features.shape)
print(g2m_edge_index.shape)
print(g2m_edge_index[0].unique().shape)
print(g2m_edge_index[1].unique().shape)
print(lat * lon)
print("Expected g2m edges", N_G2M_EDGES * fraction)

torch.Size([7719, 4])
torch.Size([2, 7719])
torch.Size([3705])
torch.Size([355])
3705
Expected g2m edges 5776.558339112344


### Verify M2G Graph

In [13]:
N_M2G_EDGES = 3114720

m2g_features = torch.load(os.path.join(graph_dir_path, "m2g_features.pt"))
m2g_edge_index = torch.load(os.path.join(graph_dir_path, "m2g_edge_index.pt"))

print(m2g_features.shape)
print(m2g_edge_index.shape)
print(m2g_edge_index[0].unique().shape)
print(m2g_edge_index[1].unique().shape)
print(lat * lon)
print("Expected m2g edges", N_M2G_EDGES * fraction)

torch.Size([11094, 4])
torch.Size([2, 11094])
torch.Size([355])
torch.Size([3705])
3705
Expected m2g edges 11115.0


### Verify against full graphcast

In [14]:
# num_grid_nodes = 
num_m2m_edges = 327660
num_m2g_edges = 3114720

```
g2m graph: Graph(num_nodes={'grid': 3705, 'mesh': 355},
      num_edges={('grid', 'g2m', 'mesh'): 7719},
      metagraph=[('grid', 'mesh', 'g2m')])
m2g graph: Graph(num_nodes={'grid': 3705, 'mesh': 355},
      num_edges={('mesh', 'm2g', 'grid'): 11094},
      metagraph=[('mesh', 'grid', 'm2g')])
mesh graph: Graph(num_nodes=355, num_edges=2584,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(4,), dtype=torch.float32)})
```

# Verify Mesh Node Subset

In [15]:
import os
import json

import numpy as np
import torch

from graphcast_mesh import Graph


graph = "uk_graphcast"
dataset = "era5_uk"

graph_dir_path = os.path.join("graphs", graph)
# os.makedirs(graph_dir_path, exist_ok=True)

data_dir_path = os.path.join("data", dataset)
icosophere_path = os.path.join(data_dir_path, "icospheres.json")

nwp_xy_path = os.path.join(data_dir_path, "static", "nwp_xy.npy")
local_lat_lon_grid = np.load(nwp_xy_path) # (2, lon, lat) or (2, x, y)
local_lat_lon_grid = torch.from_numpy(local_lat_lon_grid).permute(2, 1, 0) # (lat, lon, 2)
print(f"Local area shape: {local_lat_lon_grid.shape}")
print(f"Opened lat lon grid at {nwp_xy_path}.")

/vol/bitbucket/bet20/nlam/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Local area shape: torch.Size([65, 57, 2])
Opened lat lon grid at data/era5_uk/static/nwp_xy.npy.


In [16]:
input_res = (721, 1440) # (lat, lon)
latitudes = torch.linspace(-90, 90, steps=input_res[0])
longitudes = torch.linspace(-180, 180, steps=input_res[1] + 1)[1:]
lat_lon_grid = torch.stack(
    torch.meshgrid(latitudes, longitudes, indexing="ij"), dim=-1
) # (lat, lon, 2)
print(f"Global area shape: {lat_lon_grid.shape}")

graph = Graph(icosophere_path, lat_lon_grid, local_lat_lon_grid)

Global area shape: torch.Size([721, 1440, 2])
Opened pre-computed graph at data/era5_uk/icospheres.json.


In [17]:
g2m_graph = graph.create_g2m_graph()

g2m graph: Graph(num_nodes={'grid': 3705, 'mesh': 355},
      num_edges={('grid', 'g2m', 'mesh'): 7719},
      metagraph=[('grid', 'mesh', 'g2m')])


/vol/bitbucket/bet20/neural-lam/graphcast_mesh.py:182: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:245.)
  g2m_graph.dstdata["pos"] = torch.tensor(


In [18]:
m2g_graph = graph.create_m2g_graph()

m2g graph: Graph(num_nodes={'grid': 3705, 'mesh': 355},
      num_edges={('mesh', 'm2g', 'grid'): 11094},
      metagraph=[('mesh', 'grid', 'm2g')])


In [19]:
mesh_graph, mesh_pos = graph.create_mesh_graph(debug=True)

mesh graph: Graph(num_nodes=355, num_edges=2584,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(4,), dtype=torch.float32)})


In [20]:
mesh_pos

tensor([[ 0.5257,  0.8507,  0.0000],
        [ 0.6817,  0.7166, -0.1476],
        [ 0.4906,  0.8640, -0.1134],
        ...,
        [ 0.6366,  0.7711,  0.0090],
        [ 0.6366,  0.7711, -0.0090],
        [ 0.6262,  0.7796,  0.0000]])

In [21]:
from graphcast_utils import xyz2latlon
mesh_coords = xyz2latlon(mesh_pos)

In [30]:
np.save(
    os.path.join(graph_dir_path, "mesh_pos.npy"),
    mesh_coords.numpy().T.astype("float32"),
)

In [25]:
mesh_coords

tensor([[  0.0000,  58.2825],
        [ -8.4891,  46.4277],
        [ -6.5119,  60.4080],
        [  4.0192,  52.7328],
        [ -4.0192,  52.7328],
        [  0.0000,  46.4277],
        [  0.0000,  61.5964],
        [  3.2587,  62.7772],
        [  3.1515,  59.3076],
        [ -3.1515,  59.3076],
        [ -3.2587,  62.7772],
        [-10.0731,  61.5915],
        [  1.9471,  55.6005],
        [ -1.9471,  55.6005],
        [ -5.2773,  56.5627],
        [ -9.8948,  50.4597],
        [ -7.5302,  53.6154],
        [ -6.2056,  49.6753],
        [ -8.8260,  57.6001],
        [  0.0000,  52.7328],
        [  4.2680,  46.4277],
        [  2.0758,  49.6753],
        [ -2.0758,  49.6753],
        [ -4.2680,  46.4277],
        [  0.0000,  59.9117],
        [  1.5761,  60.4529],
        [  1.5494,  58.7861],
        [  1.6022,  62.1764],
        [  0.0000,  63.3364],
        [  3.2057,  61.0133],
        [ -1.5494,  58.7861],
        [ -1.5761,  60.4529],
        [ -4.8883,  61.5940],
        [ 

In [23]:
lon, lat = mesh_coords[:, 0], mesh_coords[:, 1]

In [24]:
print(lon.min(), lon.max(), lat.min(), lat.max())

tensor(-10.6876) tensor(4.6971) tensor(46.4277) tensor(63.6808)
